// (c) 1992-2021 Intel Corporation.                            
// Intel, the Intel logo, Intel, MegaCore, NIOS II, Quartus and TalkBack words    
// and logos are trademarks of Intel Corporation or its subsidiaries in the U.S.  
// and/or other countries. Other marks and brands may be claimed as the property  
// of others. See Trademarks on intel.com for full list of Intel trademarks or    
// the Trademarks & Brands Names Database (if Intel) or See www.Intel.com/legal (if Altera) 
// Your use of Intel Corporation's design tools, logic functions and other        
// software and tools, and its AMPP partner logic functions, and any output       
// files any of the foregoing (including device programming or simulation         
// files), and any associated documentation or information are expressly subject  
// to the terms and conditions of the Altera Program License Subscription         
// Agreement, Intel MegaCore Function License Agreement, or other applicable      
// license agreement, including, without limitation, that your use is for the     
// sole purpose of programming logic devices manufactured by Intel and sold by    
// Intel or its authorized distributors.  Please refer to the applicable          
// agreement for further details.                                                 
// Generated by Intel(R) HLS Compiler, Version 21.1.0 Build 173.3

/////////////////////////////////////////////////////////////////
// MODULE gemm_blocked_k8_latency_under_lut_internal
/////////////////////////////////////////////////////////////////
module gemm_blocked_k8_latency_under_lut_internal
(
   input logic clock,
   input logic resetn,
   input logic [31:0] in_BA0,
   input logic [31:0] in_BA1,
   input logic [31:0] in_BA2,
   input logic [31:0] in_BA3,
   input logic [31:0] in_BA4,
   input logic [31:0] in_BA5,
   input logic [31:0] in_BA6,
   input logic [31:0] in_BA7,
   input logic [31:0] in_BB0,
   input logic [31:0] in_BB1,
   input logic [31:0] in_BB2,
   input logic [31:0] in_BB3,
   input logic [31:0] in_BB4,
   input logic [31:0] in_BB5,
   input logic [31:0] in_BB6,
   input logic [31:0] in_BB7,
   input logic start,
   output logic busy,
   output logic done,
   input logic stall,
   output logic [31:0] returndata
);
   // INST gemm_blocked_k8_latency_under_lut_internal of gemm_blocked_k8_latency_under_lut_function_wrapper
   gemm_blocked_k8_latency_under_lut_function_wrapper gemm_blocked_k8_latency_under_lut_internal
   (
      .clock(clock),
      .resetn(resetn),
      .in_BA0(in_BA0),
      .in_BA1(in_BA1),
      .in_BA2(in_BA2),
      .in_BA3(in_BA3),
      .in_BA4(in_BA4),
      .in_BA5(in_BA5),
      .in_BA6(in_BA6),
      .in_BA7(in_BA7),
      .in_BB0(in_BB0),
      .in_BB1(in_BB1),
      .in_BB2(in_BB2),
      .in_BB3(in_BB3),
      .in_BB4(in_BB4),
      .in_BB5(in_BB5),
      .in_BB6(in_BB6),
      .in_BB7(in_BB7),
      .start(start),
      .busy(busy),
      .done(done),
      .stall(stall),
      .returndata(returndata)
   );

endmodule

