// (c) 1992-2021 Intel Corporation.                            
// Intel, the Intel logo, Intel, MegaCore, NIOS II, Quartus and TalkBack words    
// and logos are trademarks of Intel Corporation or its subsidiaries in the U.S.  
// and/or other countries. Other marks and brands may be claimed as the property  
// of others. See Trademarks on intel.com for full list of Intel trademarks or    
// the Trademarks & Brands Names Database (if Intel) or See www.Intel.com/legal (if Altera) 
// Your use of Intel Corporation's design tools, logic functions and other        
// software and tools, and its AMPP partner logic functions, and any output       
// files any of the foregoing (including device programming or simulation         
// files), and any associated documentation or information are expressly subject  
// to the terms and conditions of the Altera Program License Subscription         
// Agreement, Intel MegaCore Function License Agreement, or other applicable      
// license agreement, including, without limitation, that your use is for the     
// sole purpose of programming logic devices manufactured by Intel and sold by    
// Intel or its authorized distributors.  Please refer to the applicable          
// agreement for further details.                                                 
// Generated by Intel(R) HLS Compiler, Version 21.1.0 Build 173.3

/////////////////////////////////////////////////////////////////
// MODULE gemm_k8_weighted_internal
/////////////////////////////////////////////////////////////////
module gemm_k8_weighted_internal
(
   input logic clock,
   input logic resetn,
   input logic [31:0] in_A0,
   input logic [31:0] in_A1,
   input logic [31:0] in_A2,
   input logic [31:0] in_A3,
   input logic [31:0] in_A4,
   input logic [31:0] in_A5,
   input logic [31:0] in_A6,
   input logic [31:0] in_A7,
   input logic [31:0] in_B0,
   input logic [31:0] in_B1,
   input logic [31:0] in_B2,
   input logic [31:0] in_B3,
   input logic [31:0] in_B4,
   input logic [31:0] in_B5,
   input logic [31:0] in_B6,
   input logic [31:0] in_B7,
   input logic start,
   output logic busy,
   output logic done,
   input logic stall,
   output logic [31:0] returndata
);
   // INST gemm_k8_weighted_internal of gemm_k8_weighted_function_wrapper
   gemm_k8_weighted_function_wrapper gemm_k8_weighted_internal
   (
      .clock(clock),
      .resetn(resetn),
      .in_A0(in_A0),
      .in_A1(in_A1),
      .in_A2(in_A2),
      .in_A3(in_A3),
      .in_A4(in_A4),
      .in_A5(in_A5),
      .in_A6(in_A6),
      .in_A7(in_A7),
      .in_B0(in_B0),
      .in_B1(in_B1),
      .in_B2(in_B2),
      .in_B3(in_B3),
      .in_B4(in_B4),
      .in_B5(in_B5),
      .in_B6(in_B6),
      .in_B7(in_B7),
      .start(start),
      .busy(busy),
      .done(done),
      .stall(stall),
      .returndata(returndata)
   );

endmodule

