// (c) 1992-2021 Intel Corporation.                            
// Intel, the Intel logo, Intel, MegaCore, NIOS II, Quartus and TalkBack words    
// and logos are trademarks of Intel Corporation or its subsidiaries in the U.S.  
// and/or other countries. Other marks and brands may be claimed as the property  
// of others. See Trademarks on intel.com for full list of Intel trademarks or    
// the Trademarks & Brands Names Database (if Intel) or See www.Intel.com/legal (if Altera) 
// Your use of Intel Corporation's design tools, logic functions and other        
// software and tools, and its AMPP partner logic functions, and any output       
// files any of the foregoing (including device programming or simulation         
// files), and any associated documentation or information are expressly subject  
// to the terms and conditions of the Altera Program License Subscription         
// Agreement, Intel MegaCore Function License Agreement, or other applicable      
// license agreement, including, without limitation, that your use is for the     
// sole purpose of programming logic devices manufactured by Intel and sold by    
// Intel or its authorized distributors.  Please refer to the applicable          
// agreement for further details.                                                 
// Generated by Intel(R) HLS Compiler, Version 21.1.0 Build 173.3

/////////////////////////////////////////////////////////////////
// MODULE dot16_power_unconstrained_internal
/////////////////////////////////////////////////////////////////
module dot16_power_unconstrained_internal
(
   input logic clock,
   input logic resetn,
   input logic [31:0] in_a0,
   input logic [31:0] in_a1,
   input logic [31:0] in_a10,
   input logic [31:0] in_a11,
   input logic [31:0] in_a12,
   input logic [31:0] in_a13,
   input logic [31:0] in_a14,
   input logic [31:0] in_a15,
   input logic [31:0] in_a2,
   input logic [31:0] in_a3,
   input logic [31:0] in_a4,
   input logic [31:0] in_a5,
   input logic [31:0] in_a6,
   input logic [31:0] in_a7,
   input logic [31:0] in_a8,
   input logic [31:0] in_a9,
   input logic [31:0] in_b0,
   input logic [31:0] in_b1,
   input logic [31:0] in_b10,
   input logic [31:0] in_b11,
   input logic [31:0] in_b12,
   input logic [31:0] in_b13,
   input logic [31:0] in_b14,
   input logic [31:0] in_b15,
   input logic [31:0] in_b2,
   input logic [31:0] in_b3,
   input logic [31:0] in_b4,
   input logic [31:0] in_b5,
   input logic [31:0] in_b6,
   input logic [31:0] in_b7,
   input logic [31:0] in_b8,
   input logic [31:0] in_b9,
   input logic start,
   output logic busy,
   output logic done,
   input logic stall,
   output logic [31:0] returndata
);
   // INST dot16_power_unconstrained_internal of dot16_power_unconstrained_function_wrapper
   dot16_power_unconstrained_function_wrapper dot16_power_unconstrained_internal
   (
      .clock(clock),
      .resetn(resetn),
      .in_a0(in_a0),
      .in_a1(in_a1),
      .in_a10(in_a10),
      .in_a11(in_a11),
      .in_a12(in_a12),
      .in_a13(in_a13),
      .in_a14(in_a14),
      .in_a15(in_a15),
      .in_a2(in_a2),
      .in_a3(in_a3),
      .in_a4(in_a4),
      .in_a5(in_a5),
      .in_a6(in_a6),
      .in_a7(in_a7),
      .in_a8(in_a8),
      .in_a9(in_a9),
      .in_b0(in_b0),
      .in_b1(in_b1),
      .in_b10(in_b10),
      .in_b11(in_b11),
      .in_b12(in_b12),
      .in_b13(in_b13),
      .in_b14(in_b14),
      .in_b15(in_b15),
      .in_b2(in_b2),
      .in_b3(in_b3),
      .in_b4(in_b4),
      .in_b5(in_b5),
      .in_b6(in_b6),
      .in_b7(in_b7),
      .in_b8(in_b8),
      .in_b9(in_b9),
      .start(start),
      .busy(busy),
      .done(done),
      .stall(stall),
      .returndata(returndata)
   );

endmodule

