// gemm_k8_latency_unconstrained.v

// Generated using ACDS version 19.2 57

`timescale 1 ps / 1 ps
module gemm_k8_latency_unconstrained (
		input  wire        clock,      //      clock.clk
		input  wire        resetn,     //      reset.reset_n
		input  wire        start,      //       call.valid
		output wire        busy,       //           .stall
		output wire        done,       //     return.valid
		input  wire        stall,      //           .stall
		output wire [31:0] returndata, // returndata.data
		input  wire [31:0] in_A0,      //      in_A0.data
		input  wire [31:0] in_A1,      //      in_A1.data
		input  wire [31:0] in_A2,      //      in_A2.data
		input  wire [31:0] in_A3,      //      in_A3.data
		input  wire [31:0] in_A4,      //      in_A4.data
		input  wire [31:0] in_A5,      //      in_A5.data
		input  wire [31:0] in_A6,      //      in_A6.data
		input  wire [31:0] in_A7,      //      in_A7.data
		input  wire [31:0] in_B0,      //      in_B0.data
		input  wire [31:0] in_B1,      //      in_B1.data
		input  wire [31:0] in_B2,      //      in_B2.data
		input  wire [31:0] in_B3,      //      in_B3.data
		input  wire [31:0] in_B4,      //      in_B4.data
		input  wire [31:0] in_B5,      //      in_B5.data
		input  wire [31:0] in_B6,      //      in_B6.data
		input  wire [31:0] in_B7       //      in_B7.data
	);

	gemm_k8_latency_unconstrained_internal gemm_k8_latency_unconstrained_internal_inst (
		.clock      (clock),      //   input,   width = 1,      clock.clk
		.resetn     (resetn),     //   input,   width = 1,      reset.reset_n
		.start      (start),      //   input,   width = 1,       call.valid
		.busy       (busy),       //  output,   width = 1,           .stall
		.done       (done),       //  output,   width = 1,     return.valid
		.stall      (stall),      //   input,   width = 1,           .stall
		.returndata (returndata), //  output,  width = 32, returndata.data
		.in_A0      (in_A0),      //   input,  width = 32,      in_A0.data
		.in_A1      (in_A1),      //   input,  width = 32,      in_A1.data
		.in_A2      (in_A2),      //   input,  width = 32,      in_A2.data
		.in_A3      (in_A3),      //   input,  width = 32,      in_A3.data
		.in_A4      (in_A4),      //   input,  width = 32,      in_A4.data
		.in_A5      (in_A5),      //   input,  width = 32,      in_A5.data
		.in_A6      (in_A6),      //   input,  width = 32,      in_A6.data
		.in_A7      (in_A7),      //   input,  width = 32,      in_A7.data
		.in_B0      (in_B0),      //   input,  width = 32,      in_B0.data
		.in_B1      (in_B1),      //   input,  width = 32,      in_B1.data
		.in_B2      (in_B2),      //   input,  width = 32,      in_B2.data
		.in_B3      (in_B3),      //   input,  width = 32,      in_B3.data
		.in_B4      (in_B4),      //   input,  width = 32,      in_B4.data
		.in_B5      (in_B5),      //   input,  width = 32,      in_B5.data
		.in_B6      (in_B6),      //   input,  width = 32,      in_B6.data
		.in_B7      (in_B7)       //   input,  width = 32,      in_B7.data
	);

endmodule
