// dot16_original.v

// Generated using ACDS version 19.2 57

`timescale 1 ps / 1 ps
module dot16_original (
		input  wire        clock,      //      clock.clk
		input  wire        resetn,     //      reset.reset_n
		input  wire        start,      //       call.valid
		output wire        busy,       //           .stall
		output wire        done,       //     return.valid
		input  wire        stall,      //           .stall
		output wire [31:0] returndata, // returndata.data
		input  wire [31:0] in_a0,      //      in_a0.data
		input  wire [31:0] in_a1,      //      in_a1.data
		input  wire [31:0] in_a10,     //     in_a10.data
		input  wire [31:0] in_a11,     //     in_a11.data
		input  wire [31:0] in_a12,     //     in_a12.data
		input  wire [31:0] in_a13,     //     in_a13.data
		input  wire [31:0] in_a14,     //     in_a14.data
		input  wire [31:0] in_a15,     //     in_a15.data
		input  wire [31:0] in_a2,      //      in_a2.data
		input  wire [31:0] in_a3,      //      in_a3.data
		input  wire [31:0] in_a4,      //      in_a4.data
		input  wire [31:0] in_a5,      //      in_a5.data
		input  wire [31:0] in_a6,      //      in_a6.data
		input  wire [31:0] in_a7,      //      in_a7.data
		input  wire [31:0] in_a8,      //      in_a8.data
		input  wire [31:0] in_a9,      //      in_a9.data
		input  wire [31:0] in_b0,      //      in_b0.data
		input  wire [31:0] in_b1,      //      in_b1.data
		input  wire [31:0] in_b10,     //     in_b10.data
		input  wire [31:0] in_b11,     //     in_b11.data
		input  wire [31:0] in_b12,     //     in_b12.data
		input  wire [31:0] in_b13,     //     in_b13.data
		input  wire [31:0] in_b14,     //     in_b14.data
		input  wire [31:0] in_b15,     //     in_b15.data
		input  wire [31:0] in_b2,      //      in_b2.data
		input  wire [31:0] in_b3,      //      in_b3.data
		input  wire [31:0] in_b4,      //      in_b4.data
		input  wire [31:0] in_b5,      //      in_b5.data
		input  wire [31:0] in_b6,      //      in_b6.data
		input  wire [31:0] in_b7,      //      in_b7.data
		input  wire [31:0] in_b8,      //      in_b8.data
		input  wire [31:0] in_b9       //      in_b9.data
	);

	dot16_original_internal dot16_original_internal_inst (
		.clock      (clock),      //   input,   width = 1,      clock.clk
		.resetn     (resetn),     //   input,   width = 1,      reset.reset_n
		.start      (start),      //   input,   width = 1,       call.valid
		.busy       (busy),       //  output,   width = 1,           .stall
		.done       (done),       //  output,   width = 1,     return.valid
		.stall      (stall),      //   input,   width = 1,           .stall
		.returndata (returndata), //  output,  width = 32, returndata.data
		.in_a0      (in_a0),      //   input,  width = 32,      in_a0.data
		.in_a1      (in_a1),      //   input,  width = 32,      in_a1.data
		.in_a10     (in_a10),     //   input,  width = 32,     in_a10.data
		.in_a11     (in_a11),     //   input,  width = 32,     in_a11.data
		.in_a12     (in_a12),     //   input,  width = 32,     in_a12.data
		.in_a13     (in_a13),     //   input,  width = 32,     in_a13.data
		.in_a14     (in_a14),     //   input,  width = 32,     in_a14.data
		.in_a15     (in_a15),     //   input,  width = 32,     in_a15.data
		.in_a2      (in_a2),      //   input,  width = 32,      in_a2.data
		.in_a3      (in_a3),      //   input,  width = 32,      in_a3.data
		.in_a4      (in_a4),      //   input,  width = 32,      in_a4.data
		.in_a5      (in_a5),      //   input,  width = 32,      in_a5.data
		.in_a6      (in_a6),      //   input,  width = 32,      in_a6.data
		.in_a7      (in_a7),      //   input,  width = 32,      in_a7.data
		.in_a8      (in_a8),      //   input,  width = 32,      in_a8.data
		.in_a9      (in_a9),      //   input,  width = 32,      in_a9.data
		.in_b0      (in_b0),      //   input,  width = 32,      in_b0.data
		.in_b1      (in_b1),      //   input,  width = 32,      in_b1.data
		.in_b10     (in_b10),     //   input,  width = 32,     in_b10.data
		.in_b11     (in_b11),     //   input,  width = 32,     in_b11.data
		.in_b12     (in_b12),     //   input,  width = 32,     in_b12.data
		.in_b13     (in_b13),     //   input,  width = 32,     in_b13.data
		.in_b14     (in_b14),     //   input,  width = 32,     in_b14.data
		.in_b15     (in_b15),     //   input,  width = 32,     in_b15.data
		.in_b2      (in_b2),      //   input,  width = 32,      in_b2.data
		.in_b3      (in_b3),      //   input,  width = 32,      in_b3.data
		.in_b4      (in_b4),      //   input,  width = 32,      in_b4.data
		.in_b5      (in_b5),      //   input,  width = 32,      in_b5.data
		.in_b6      (in_b6),      //   input,  width = 32,      in_b6.data
		.in_b7      (in_b7),      //   input,  width = 32,      in_b7.data
		.in_b8      (in_b8),      //   input,  width = 32,      in_b8.data
		.in_b9      (in_b9)       //   input,  width = 32,      in_b9.data
	);

endmodule
