// stencil5_weighted.v

// Generated using ACDS version 19.2 57

`timescale 1 ps / 1 ps
module stencil5_weighted (
		input  wire        clock,      //      clock.clk
		input  wire        resetn,     //      reset.reset_n
		input  wire        start,      //       call.valid
		output wire        busy,       //           .stall
		output wire        done,       //     return.valid
		input  wire        stall,      //           .stall
		output wire [31:0] returndata, // returndata.data
		input  wire [31:0] in_center,  //  in_center.data
		input  wire [31:0] in_east,    //    in_east.data
		input  wire [31:0] in_north,   //   in_north.data
		input  wire [31:0] in_south,   //   in_south.data
		input  wire [31:0] in_west     //    in_west.data
	);

	stencil5_weighted_internal stencil5_weighted_internal_inst (
		.clock      (clock),      //   input,   width = 1,      clock.clk
		.resetn     (resetn),     //   input,   width = 1,      reset.reset_n
		.start      (start),      //   input,   width = 1,       call.valid
		.busy       (busy),       //  output,   width = 1,           .stall
		.done       (done),       //  output,   width = 1,     return.valid
		.stall      (stall),      //   input,   width = 1,           .stall
		.returndata (returndata), //  output,  width = 32, returndata.data
		.in_center  (in_center),  //   input,  width = 32,  in_center.data
		.in_east    (in_east),    //   input,  width = 32,    in_east.data
		.in_north   (in_north),   //   input,  width = 32,   in_north.data
		.in_south   (in_south),   //   input,  width = 32,   in_south.data
		.in_west    (in_west)     //   input,  width = 32,    in_west.data
	);

endmodule
