// fir8_latency_under_lut.v

// Generated using ACDS version 19.2 57

`timescale 1 ps / 1 ps
module fir8_latency_under_lut (
		input  wire        clock,      //      clock.clk
		input  wire        resetn,     //      reset.reset_n
		input  wire        start,      //       call.valid
		output wire        busy,       //           .stall
		output wire        done,       //     return.valid
		input  wire        stall,      //           .stall
		output wire [31:0] returndata, // returndata.data
		input  wire [31:0] in_x0,      //      in_x0.data
		input  wire [31:0] in_x1,      //      in_x1.data
		input  wire [31:0] in_x2,      //      in_x2.data
		input  wire [31:0] in_x3,      //      in_x3.data
		input  wire [31:0] in_x4,      //      in_x4.data
		input  wire [31:0] in_x5,      //      in_x5.data
		input  wire [31:0] in_x6,      //      in_x6.data
		input  wire [31:0] in_x7       //      in_x7.data
	);

	fir8_latency_under_lut_internal fir8_latency_under_lut_internal_inst (
		.clock      (clock),      //   input,   width = 1,      clock.clk
		.resetn     (resetn),     //   input,   width = 1,      reset.reset_n
		.start      (start),      //   input,   width = 1,       call.valid
		.busy       (busy),       //  output,   width = 1,           .stall
		.done       (done),       //  output,   width = 1,     return.valid
		.stall      (stall),      //   input,   width = 1,           .stall
		.returndata (returndata), //  output,  width = 32, returndata.data
		.in_x0      (in_x0),      //   input,  width = 32,      in_x0.data
		.in_x1      (in_x1),      //   input,  width = 32,      in_x1.data
		.in_x2      (in_x2),      //   input,  width = 32,      in_x2.data
		.in_x3      (in_x3),      //   input,  width = 32,      in_x3.data
		.in_x4      (in_x4),      //   input,  width = 32,      in_x4.data
		.in_x5      (in_x5),      //   input,  width = 32,      in_x5.data
		.in_x6      (in_x6),      //   input,  width = 32,      in_x6.data
		.in_x7      (in_x7)       //   input,  width = 32,      in_x7.data
	);

endmodule
