// conv3x3_latency_unconstrained.v

// Generated using ACDS version 19.2 57

`timescale 1 ps / 1 ps
module conv3x3_latency_unconstrained (
		input  wire        clock,      //      clock.clk
		input  wire        resetn,     //      reset.reset_n
		input  wire        start,      //       call.valid
		output wire        busy,       //           .stall
		output wire        done,       //     return.valid
		input  wire        stall,      //           .stall
		output wire [31:0] returndata, // returndata.data
		input  wire [31:0] in_p00,     //     in_p00.data
		input  wire [31:0] in_p01,     //     in_p01.data
		input  wire [31:0] in_p02,     //     in_p02.data
		input  wire [31:0] in_p10,     //     in_p10.data
		input  wire [31:0] in_p11,     //     in_p11.data
		input  wire [31:0] in_p12,     //     in_p12.data
		input  wire [31:0] in_p20,     //     in_p20.data
		input  wire [31:0] in_p21,     //     in_p21.data
		input  wire [31:0] in_p22      //     in_p22.data
	);

	conv3x3_latency_unconstrained_internal conv3x3_latency_unconstrained_internal_inst (
		.clock      (clock),      //   input,   width = 1,      clock.clk
		.resetn     (resetn),     //   input,   width = 1,      reset.reset_n
		.start      (start),      //   input,   width = 1,       call.valid
		.busy       (busy),       //  output,   width = 1,           .stall
		.done       (done),       //  output,   width = 1,     return.valid
		.stall      (stall),      //   input,   width = 1,           .stall
		.returndata (returndata), //  output,  width = 32, returndata.data
		.in_p00     (in_p00),     //   input,  width = 32,     in_p00.data
		.in_p01     (in_p01),     //   input,  width = 32,     in_p01.data
		.in_p02     (in_p02),     //   input,  width = 32,     in_p02.data
		.in_p10     (in_p10),     //   input,  width = 32,     in_p10.data
		.in_p11     (in_p11),     //   input,  width = 32,     in_p11.data
		.in_p12     (in_p12),     //   input,  width = 32,     in_p12.data
		.in_p20     (in_p20),     //   input,  width = 32,     in_p20.data
		.in_p21     (in_p21),     //   input,  width = 32,     in_p21.data
		.in_p22     (in_p22)      //   input,  width = 32,     in_p22.data
	);

endmodule
