// (c) 1992-2021 Intel Corporation.                            
// Intel, the Intel logo, Intel, MegaCore, NIOS II, Quartus and TalkBack words    
// and logos are trademarks of Intel Corporation or its subsidiaries in the U.S.  
// and/or other countries. Other marks and brands may be claimed as the property  
// of others. See Trademarks on intel.com for full list of Intel trademarks or    
// the Trademarks & Brands Names Database (if Intel) or See www.Intel.com/legal (if Altera) 
// Your use of Intel Corporation's design tools, logic functions and other        
// software and tools, and its AMPP partner logic functions, and any output       
// files any of the foregoing (including device programming or simulation         
// files), and any associated documentation or information are expressly subject  
// to the terms and conditions of the Altera Program License Subscription         
// Agreement, Intel MegaCore Function License Agreement, or other applicable      
// license agreement, including, without limitation, that your use is for the     
// sole purpose of programming logic devices manufactured by Intel and sold by    
// Intel or its authorized distributors.  Please refer to the applicable          
// agreement for further details.                                                 
// Generated by Intel(R) HLS Compiler, Version 21.1.0 Build 173.3

typedef struct packed {
 logic [31:0] in_b9;
 logic [31:0] in_b8;
 logic [31:0] in_b7;
 logic [31:0] in_b6;
 logic [31:0] in_b5;
 logic [31:0] in_b4;
 logic [31:0] in_b3;
 logic [31:0] in_b2;
 logic [31:0] in_b15;
 logic [31:0] in_b14;
 logic [31:0] in_b13;
 logic [31:0] in_b12;
 logic [31:0] in_b11;
 logic [31:0] in_b10;
 logic [31:0] in_b1;
 logic [31:0] in_b0;
 logic [31:0] in_a9;
 logic [31:0] in_a8;
 logic [31:0] in_a7;
 logic [31:0] in_a6;
 logic [31:0] in_a5;
 logic [31:0] in_a4;
 logic [31:0] in_a3;
 logic [31:0] in_a2;
 logic [31:0] in_a15;
 logic [31:0] in_a14;
 logic [31:0] in_a13;
 logic [31:0] in_a12;
 logic [31:0] in_a11;
 logic [31:0] in_a10;
 logic [31:0] in_a1;
 logic [31:0] in_a0;
} struct_dot16_latency_unconstrained_inputs;



